# Generated by Django 2.0.2 on 2018-02-26 23:05

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="App",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="TaskLog",
            fields=[
                (
                    "task_id",
                    models.CharField(max_length=256, primary_key=True, serialize=False),
                ),
                ("when", models.DateTimeField()),
                ("success", models.NullBooleanField()),
                ("description", models.CharField(max_length=256)),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apps.App"
                    ),
                ),
            ],
        ),
    ]
