# Generated by Django 5.2 on 2025-04-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0002_app_github_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasklog",
            name="success",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
