# Generated by Django 5.2.1 on 2025-05-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0003_alter_tasklog_success"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="name",
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
